### ISSUE TITLE
Please create an AppData file for Tagaini Jisho

### ISSUE THREAD

**Issue by hughsie** [Gnurou/tagainijisho#105]
Please consider writing and installing an AppData file with the application description and some screenshots, else Tagaini Jisho looks really bad in the GNOME and KDE Software Centers. We'd love to showcase more applications, but without the extra data file we can't. See http://people.freedesktop.org/~hughsient/appdata/ for details; thanks!

Richard

**Comment by Gnurou** [comment]
Wow, can't believe it took me so long to come back to this. Anyway, this is finally done, sorry for the delay!
