### ISSUE TITLE
Cannot build using AUR

### ISSUE THREAD

**Issue by belthsazarliem** [Gnurou/tagainijisho#126]
I am using Manjaro Linux and yesterday I tried to install Tagaini Jisho using yaourt (AUR). But sadly it failed miserably. I paste the log for CMake.

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: CMAKE_C_COMPILER-NOTFOUND 
Build flags: -march=x86-64;-mtune=generic;-O2;-pipe;-fstack-protector-strong;--param=ssp-buffer-size=4
Id flags: 

The output was:
No such file or directory

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: CMAKE_C_COMPILER-NOTFOUND 
Build flags: -march=x86-64;-mtune=generic;-O2;-pipe;-fstack-protector-strong;--param=ssp-buffer-size=4
Id flags: -c

The output was:
No such file or directory

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: CMAKE_C_COMPILER-NOTFOUND 
Build flags: -march=x86-64;-mtune=generic;-O2;-pipe;-fstack-protector-strong;--param=ssp-buffer-size=4
Id flags: -Aa

The output was:
No such file or directory

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: CMAKE_CXX_COMPILER-NOTFOUND 
Build flags: -march=x86-64;-mtune=generic;-O2;-pipe;-fstack-protector-strong;--param=ssp-buffer-size=4
Id flags: 

The output was:
No such file or directory

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: CMAKE_CXX_COMPILER-NOTFOUND 
Build flags: -march=x86-64;-mtune=generic;-O2;-pipe;-fstack-protector-strong;--param=ssp-buffer-size=4
Id flags: -c

The output was:
No such file or directory

So weird, because I previously succeed on building the package. I did a reinstall of Manjaro and then tried to install Tagaini, but this happened. I also had checked the files which are said 'no such file or directory', but I found them anyway. Can you help me solve this issue?

**Comment by firatakandere** [comment]
It's not about he tagainijisho but it means you don't have the required compilers on your system. Run this code:

`sudo pacman -S base-devel --needed`

**Comment by belthsazarliem** [comment]
thanks. I'll try it later.

**Comment by belthsazarliem** [comment]
so, the mistake is on my part. forgot about the lost GCC. I'll close this issue.
