### ISSUE TITLE
JLPT word lists contain obscure words

### ISSUE THREAD

**Issue by krofna** [Gnurou/tagainijisho#130]
I assumed that it was compiled using kana matching because for example:

* N5 list has both どう (how) and どう (command used to stop a horse)
* N4 list has 皆 and 御名, けれど (but) and ケレド (credo, "I believe" in latin), と and 劫

There are more as well.

**Comment by Gnurou** [comment]
Hi,

These are incorrect of course. Could you try to list all the entries you can find, preferably by their JMdict ID? (you can display it in Preferences -> Vocabulary entries -> Display -> Basic information) Then I will remove them from the JLPT lists.

Thanks!

**Comment by krofna** [comment]
1021180
2257550
1084000
1923080
2021190
2198520
2255350
2409210
1647970
1578910
2482240
2029780
1331020
1570970
1580130
1476550
1308080
2662700

These are obvious ones I came across. There may be more.

**Comment by Gnurou** [comment]
Wow, some of these were really bad. This is now fixed, thanks for taking the time to make this list!
If you find further and want to make a merge request, the files containing these are src/core/jmdict/jlpt*.csv (one entry ID per line).
