### ISSUE TITLE
"(kokuji)" is listed as the 4th definition of 辻 in the summary

### ISSUE THREAD

**Issue by ScoreUnder** [Gnurou/tagainijisho#131]
![Screenshot](http://a.pomf.se/kyordf.png)

This is a cosmetic issue

**Comment by Gnurou** [comment]
The problem comes from kandjidic2, since it lists (kokuji) as a meaning. Apparently it is well-known since a while: https://groups.yahoo.com/neo/groups/edict-jmdict/conversations/topics/433
This needs to be fixed upstream, Tagaini just displays the data it is fed with. Closing this issue here.
