### ISSUE TITLE
Overwriting a file when exporting user data fails

### ISSUE THREAD

**Issue by cclassic** [Gnurou/tagainijisho#132]
**How to reproduce:**
Export a user db, make a change, export again to the same file, import it.

**Expected behavior:**
To see the db in the state after making the change.

**Displayed behavior:**
The data base is back to the initial export.

*Tested using git commit 1859907bcddf5b24ad701079bf393f152a1b3b92 on Arch Linux.*

**Comment by cclassic** [comment]
Problem lies in MainWindow.cc, line 239. QFile::copy() does not overwrite existing files.

Simply deleting the file beforehand solves the problem. Here's a patch:
```
diff --git a/src/gui/MainWindow.cc b/src/gui/MainWindow.cc
index 4ef2935..d1be895 100644
--- a/src/gui/MainWindow.cc
+++ b/src/gui/MainWindow.cc
@@ -236,6 +236,7 @@ void MainWindow::exportUserData()
 	if (to.isEmpty()) return;
 
 	QFile dataFile(Database::instance()->userDBFile());
+        QFile(to).remove();
 	dataFile.copy(to);
 }
 

```

**Comment by Gnurou** [comment]
Excellent, thanks! Would you send a pull request so you can get
appropriate credit? Otherwise I will just integrate this patch as-is.

**Comment by cclassic** [comment]
I also wanted to update the translations (en and de) for the error message I added. That, however, resulted in a really large commit. (Adding many lines like  ```<location filename="../src/gui/ui_AboutDialog.h" line="+1"/>``` to the .ts). Probably because I use a later version of lupdate. Should I still commit it as well?

**Comment by Gnurou** [comment]
Closing the issue as your commit is merged, thanks! Don't worry about the translations, they are updated automatically whenever I prepare for a release.
