### ISSUE TITLE
Problème de build à cause de kanjidic2.xml.gz

### ISSUE THREAD

**Issue by twatan** [Gnurou/tagainijisho#136]
Bonjour,

Quand j'ai fait un build, j'ai eu ce message d'erreur.

```
-- Downloading Kanjidic2 from http://www.csse.monash.edu.au/~jwb/kanjidic2/kanjidic2.xml.gz
gunzip: /Users/watanabe/git/tagainijisho/3rdparty/kanjidic2.xml.gz: unexpected end of file
CMake Error at src/core/kanjidic2/CMakeLists.txt:13 (MESSAGE):
  Unable to run [/usr/bin/gunzip
  /Users/watanabe/git/tagainijisho/3rdparty/kanjidic2.xml.gz].  Reported
  error was [1]
```

J'ai l'impression que ce lien ne fonctionne pas. (http://www.csse.monash.edu.au/~jwb/kanjidic2/kanjidic2.xml.gz)

Je l'ai remplacé par ce lien (http://www.edrdg.org/kanjidic/kanjidic2.xml.gz), et là tout va bien.

```
-set(KANJIDIC2_SOURCE http://www.csse.monash.edu.au/~jwb/kanjidic2/kanjidic2.xml.gz)
+set(KANJIDIC2_SOURCE http://www.edrdg.org/kanjidic/kanjidic2.xml.gz)
```
Sinon merci pour ce logiciel.

**Comment by Gnurou** [comment]
L'ancien lien semble toujours être fonctionnel de mon côté, mais il est vrai que la page du kanjidic2 référence edrdg.org. J'ai donc mis le lien à jour, merci d'avoir rapporté ce problème!
