### ISSUE TITLE
can't get rid of system language

### ISSUE THREAD

**Issue by ayoungdude** [Gnurou/tagainijisho#138]
Hi,
I'm using a French computer but I want Tagaini jisho to be in English.

I changed the preferred dictionary to English --> still had French

I forced English definitions --> the French was still there so it was distracting

I tried to delete anything with FR in the tagaini jisho folder --> nothing changed oddly enough

tried setting the number of definitions in cache to 0 ---> nothing then 1 --> still nothing 

I don't get it, why haven't I at least broken the program?

**Comment by Gnurou** [comment]
Hi,

Have you restarted the program after changing the languages settings, as mentioned in the preferences window?

**Comment by ayoungdude** [comment]
yep restarted the program after every step sorry should have said that

**Comment by Gnurou** [comment]
What system are you using? Windows, Mac OS, Linux?

**Comment by ayoungdude** [comment]
Windows 8.1 French professionnel edition.

**Comment by Gnurou** [comment]
Thanks - one thing you don't mention in your original post is whether you have tried changing the "preferred UI language" setting (langue préférée pour l'interface in French). I suppose you have, but checking just in case.

I have tried setting my system language to French, and forcing the UI setting to English. The UI shows up in English, but the dictionary entries are still in French - and remain that way even if I set the preferred dictionary language to English. That seems to be a bug - is it the one you are experiencing?

**Comment by ayoungdude** [comment]
yes both the GUI and the dictionary are in English see attached picture.
Just out of curiosity I tried to put the GUI in french and that didn't work
either. I'm wondering if there isn't an old settings file interfering with
the program but I wouldn't know where to look for that.
BTW is there a way to just delete the French dictionary so that the program
just doesn't load French entries or would that crash just Tagaini Jisho?

On 13 May 2015 at 07:20, Alexandre Courbot <notifications@github.com> wrote:

> Thanks - one thing you don't mention in your original post is whether you
> have tried changing the "preferred UI language" setting (langue préférée
> pour l'interface in French). I suppose you have, but checking just in case.
>
> I have tried setting my system language to French, and forcing the UI
> setting to English. The UI shows up in English, but the dictionary entries
> are still in French - and remain that way even if I set the preferred
> dictionary language to English. That seems to be a bug - is it the one you
> are experiencing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Gnurou/tagainijisho/issues/138#issuecomment-101516313>
> .
>



-- 

[image: --]
Alexander Young

freelance English teacher
[image: http://]about.me/ayoungdude
<http://about.me/ayoungdude?promo=email_sig>

**Comment by Gnurou** [comment]
I don't think Tagaini would be very happy if you deleted a dictionary file. Better to wait until the next release ; now that I understand what the problem is I should come with a fix quickly. Thanks for reporting!

**Comment by ayoungdude** [comment]
Thanks for looking into this!

On 13 May 2015 at 08:07, Alexandre Courbot <notifications@github.com> wrote:

> I don't think Tagaini would be very happy if you deleted a dictionary
> file. Better to wait until the next release ; now that I understand what
> the problem is I should come with a fix quickly. Thanks for reporting!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Gnurou/tagainijisho/issues/138#issuecomment-101524481>
> .
>



-- 

[image: --]
Alexander Young

freelance English teacher
[image: http://]about.me/ayoungdude
<http://about.me/ayoungdude?promo=email_sig>

**Comment by noidexe** [comment]
Same problem here. I'm using Windows 10. My computer is in English but the region is set to Argentina(we speak Spanish here). 
I can't get rid of the Spanish definitions when I search. I've set GUI and preferred dictionary to English and I tried setting and unsetting "Always show English definitions"

**Comment by taimon** [comment]
On my Windows Installation, Tagaini Jisho creates a copy of the dictionaries for the local user in: %LOCALAPPDATA%\VirtualStore\Program Files (x86)\Tagaini Jisho
But this might depend on your installation path of Tagaini Jisho.
Deleting or renaming the relevant files in both directories (VirtualStore + Installation Folder) seems to work for me.
