### ISSUE TITLE
[OSX] Preference Window Size

### ISSUE THREAD

**Issue by stonerl** [Gnurou/tagainijisho#140]
The Preference Window's initial size is to small and needs to be resized everytime.

![screen shot 2015-05-06 at 13 23 57](https://cloud.githubusercontent.com/assets/2091312/7492342/6f2d32cc-f3f3-11e4-8ad3-8cf3afb34d1f.png)

**Comment by Akeru** [comment]
Seems like #67. Which version are you using ?

**Comment by stonerl** [comment]
1.0.3

**Comment by stonerl** [comment]
Sorry I just figured out that I had 1.0.1 and 1.0.3 installed and that this is fixed with 1.0.3.
