### ISSUE TITLE
romaji availability

### ISSUE THREAD

**Issue by eigoonline** [Gnurou/tagainijisho#145]
I can read hiragana but not katakana and kanji. I think it would be more helpful for many beginners if you can put a romaji for each japanese words using japanese characters. this way, we will be able to practice our skills in reading japanese characters and at the same time learn the meaning of the words. thank you :)

**Comment by Gnurou** [comment]
Reading katakana is the very basic of Japanese - there is no point in starting studying kanji if one cannot read them. The romaji feature is absent by design, so students of japanese do things in the right order.

**Comment by eigoonline** [comment]
thanks! i understand!
