### ISSUE TITLE
1.0.3 deb looks in wrong location for dictionary files

### ISSUE THREAD

**Issue by rpglover64** [Gnurou/tagainijisho#147]
Installing the unofficial deb (at least until Debian unstable picks it up) from [here](http://www.tagaini.net/download) and running `tagainijisho` gives

```
Fatal: kanjidic2 plugin fatal error: cannot find main database file!
```

Running `strace -elstat tagainijisho` reveals that the program is looking for `/usr/local/share/tagainijisho/kanjidic2.db`, but the deb installs the dictionary to `/usr/share/tagainijisho/kanjidic2.db`

**Comment by Gnurou** [comment]
Should be fixed now - I will try to update the binaries, or even better make an actual release!
