### ISSUE TITLE
1.0.3 exe can't be downloaded

### ISSUE THREAD

**Issue by skyvory** [Gnurou/tagainijisho#150]
Can't download the exe from https://github.com/Gnurou/tagainijisho/releases/download/1.0.3/tagainijisho-1.0.3.exe
"exe part could not be saved, because the source file could not be read."
Tried download with Windows 10 firefox and chrome. Both failed.

**Comment by firatakandere** [comment]
I have just downloaded and installed the file. It works fine. It might be because that the content delivery network of github failed or your ISP.

**Comment by skyvory** [comment]
Thanks for the info.
Turned out avast antivirus interrupted the download. It's downloading fine while (temporarily) disabling it.
