### ISSUE TITLE
It wouldn't recognize romaji of small kana

### ISSUE THREAD

**Issue by Raymai97** [Gnurou/tagainijisho#151]
For example, the romaji of ファイル is supposed to be 'fairu' ('fu' taking small 'a' become 'fa'), but Tagaini Jisho wouldn't recognize it. I have to type either in Katakana, or the weird alternative romaji 'fulairu', in order to search the word in Tagaini Jisho.

It would be great if it will recognize these type of romaji.

**Comment by Gnurou** [comment]
Indeed. Seems like https://github.com/Gnurou/tagainijisho/pull/153/ is already attempting to fix this. I would like to turn it into a more general fix for the fact we do not follow hepburn romanization properly before commiting it, but it seems like this will easily be fixed. Thanks for reporting.
