### ISSUE TITLE
Entrainement flashcards

### ISSUE THREAD

**Issue by Inobak** [Gnurou/tagainijisho#154]
Salut,
Est-ce que ce serait possible de faire en sorte de pouvoir créer des listes de révisions uniquement à partir de caractères que j'ai séléctionné avec shift+clic, et aussi ajouter la possibilité de réviser à partir des listes que l'ont créer (sur le coté gauche) ?

**Comment by Gnurou** [comment]
Bonjour,

En rusant un peu (par exemple en assignant un tag unique à la liste des entrées sélectionnées et en révisant sur ce tag), c'est tout à fait faisable.

Concernant les listes du côté gauche, c'est malheureusement un peu plus compliqué ; mais la même astuce du tag peut là encore être utilisée.
