### ISSUE TITLE
Incorrect components listed for kanji 勇 .

### ISSUE THREAD

**Issue by fontfish** [Gnurou/tagainijisho#156]
The kanji 勇 “Brave” has the following components listed:
マ: katakana "ma"
男: male

The correct components, as far as I am aware, are “甬” and “力”, which give pronunciation and meaning. It seems “マ” and “男” are often taught in Japanese schools but are incorrect. For clarification, I recommend taking a look at the Glyphwiki page listing traditional and variant forms of this kanji.
http://en.glyphwiki.org/wiki/u52c7

Wiktionary also lists the correct components.
https://en.wiktionary.org/wiki/%E5%8B%87

Other sources:
異体字の世界 “The World of Kanji Variants” (Japanese book)

**Comment by firatakandere** [comment]
TagainiJisho uses [KanjiVG](https://github.com/KanjiVG/kanjivg/issues). You should open this issue on KanjiVG: https://github.com/KanjiVG/kanjivg/issues

**Comment by fontfish** [comment]
OK. Thanks for letting me know (I should have taken a proper look at that beforehand). Will do.
