### ISSUE TITLE
Error when starting Tagaini

### ISSUE THREAD

**Issue by halcyon19** [Gnurou/tagainijisho#162]
I'm using Windows 8.1 
When I start the program, this error is returned :

kanjidic2 plugin fatal error : cannot find main database file
Uncoverable error, the program will now exit.

I then uninstalled the program and deleted these remaining files :  
Users/myusername/AppData/Local/VirtualStore/Program Files (x86)/Tagaini Jisho/user.db
Users/myusername/AppData/Local/Tagaini Jisho/jmdict.db
                                                                              jmdict-en.db
                                                                              kanjidic2.db
                                                                              kanjidic2-en.db

After reinstalling the program I can run it, but only once. The second time I run the program I get the same error.
If I want to run it again I have to reiterate the same process : uninstall, deletes the files, reinstall.
I can no longer use Tagaini efficiently since importing data requires the program to close and restart.

**Comment by Gnurou** [comment]
Hi,

This definitely should not happen. What version of Tagaini are you using?

**Comment by halcyon19** [comment]
I'm using 1.0.3 version.
I solved the problem by cleaning my computer with AdwareCleaner and MalwareBytes.

**Comment by Gnurou** [comment]
Alright - sounds like the issue was not related to Tagaini then. Closing this issue.
