### ISSUE TITLE
Make the components search (Ctrl+J) persistent

### ISSUE THREAD

**Issue by YamashitaRen** [Gnurou/tagainijisho#169]
I think this feature request will be easier to understand if I expose my usercase.

I'm learning the kanjis through Heisig.
Bumped in 打 minutes ago. I don't know it yet.
But I know 手 and 丁.

Currently I have to search "hand". Select 手 and copy it.
Search "house", select 丁, copy it.
Open the components search window, paste 丁. Open my clipboard, select 手, paste it.
I now have 打.

I have to rely on this process because if I go back to the main window after opening the components search, the components search windows will disappear and everything that I written there with it.

Now, for the feature request, I see two ways of ~fixing~ it :
- Allowing the user to detach/attach the components search window (like the F2 main window) instead of having it pop up.
- Making the kanji written in the components search window persistent for the current session.

What do you think ?

**Comment by YamashitaRen** [comment]
Just found a workaround : 
I can open two tagainijisho windows.
The "search" tab opened in one, the "kanji" tab opened in the second. It will address my issue.

**Comment by roxxxorzz** [comment]
i assume you're using a japanese IME keyboard right? or at least you can type japanese characters? you can learn every japanese radical's sounds, or at least one sound you can use to type them, and then you can just type it into the kanji search component box.

**Comment by YamashitaRen** [comment]
Yeah that's a solution but it requires learning at least a sound :D 
For now, I'm focusing on learning the meanings.

But, like I said in my previous comment, this is not really an issue since I can simply open two tagainijisho windows :)
