### ISSUE TITLE
JMdict tags are displayed inconsistently

### ISSUE THREAD

**Issue by krofna** [Gnurou/tagainijisho#173]
For example, all three senses of つく have the same tags in jmdict, namely [v5k,vt][uk]. But in Tagaini Jisho the first sense has all three tags, the second sense has [uk] only and the third sense has no tags at all. Many other words have the same issue. See screenshot:
![screenshot_20160714_183657](https://cloud.githubusercontent.com/assets/1102695/16847585/086c75b0-49f2-11e6-9a58-3dd24639087c.png)

**Comment by ninjadrm** [comment]
Are you sure? My 'jmdict' downloaded this week has:
`
<sense>
<pos>&v5k;</pos>
<pos>&vt;</pos>
<misc>&uk;</misc>
<gloss>to breathe out</gloss>
<gloss>to breathe</gloss>
</sense>
<sense>
<misc>&uk;</misc>
<gloss>to tell (a lie)</gloss>
<gloss>to use (foul language)</gloss>
</sense>
<sense>
<xref>吐く・はく・1</xref>
<misc>&uk;</misc>
<gloss>to vomit</gloss>
<gloss>to throw up</gloss>
<gloss>to spit up</gloss>
</sense>
<sense>
`

Looks OK to me in your screenshot and in my current version.

**Comment by krofna** [comment]
That's weird. Look at [jmdictdb.](http://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&q=1444150)

**Comment by Gnurou** [comment]
I am in the (slow) process of fixing this one. What happened is that some time ago the number of senses has gone over 64, and I used to code the senses as a 64-bits mask for easy matching in the database.

So I need to split the senses mask into several ones, and since this is used all over the code it is a bit of a chore.

**Comment by Gnurou** [comment]
This issue should now be fixed (no release including the fix as of now, though).
