### ISSUE TITLE
"Part of speech" vocabulary filter is broken

### ISSUE THREAD

**Issue by krofna** [Gnurou/tagainijisho#176]
e.g. if you select v2g-s tag you get 3425 words, most of which do not have that tag at all

**Comment by Gnurou** [comment]
I'm aware of this issue. This is because the number of parts of speech exceeded the size of the bit-field I was using to encode then (64-bits), so some of them are now broken. I need to add more fields to the database to fix this. Thanks for reporting!

**Comment by Gnurou** [comment]
Forgot to update this issue but it has been fixed by switching to using as many fields as needed to store the POS. POS lookups should now work as expected.
