### ISSUE TITLE
version 'Qt_5' not found (required by tagainijisho)

### ISSUE THREAD

**Issue by hessaum** [Gnurou/tagainijisho#189]
Could find a working solution anywhere for related problems. After compiling and running `make install` successfully I receive the following while trying to run `tagainijisho`

`tagainijisho: /usr/lib/x86_64-linux-gnu/libQt5Network.so.5: version "Qt_5' not found (required by tagainijisho)`
`tagainijisho: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version 'Qt_5' not found (required by tagainijisho)`
`tagainijisho: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version 'Qt_5.6' not found (required by tagainijisho)`
`tagainijisho: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version 'Qt_5' not found (required by tagainijisho)`
`tagainijisho: /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so.5: version 'Qt_5' not found (required by tagainijisho)`
`tagainijisho: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5: version 'Qt_5' not found (required by tagainijisho)`

`qmake` and `qt` are all up to date. Im guessing this is possibly a pathing issue, but im unsure as to how best to resolve it.

**Comment by Gnurou** [comment]
Qmake? You are supposed to use CMake to compile Tagaini. What distro are you using and which version of Tagaini is this?

**Comment by Gnurou** [comment]
Got info about your distro from the other issues. From you error it seems like you are compiling from Git and not from a release. Make sure the Qt5 packages are installed on your system (not sure what they are named on Mint), as it seems like they are missing somehow.

I don't understand how you could build Tagaini without them installed though, so that's quite weird.

**Comment by Gnurou** [comment]
After googling your error a bit, it seems to be due to the fact you have 2 versions of Qt installed on your system - could it be that you compiled Qt yourself?

**Comment by baimafeima** [comment]
Is Tagaini already fully ported to Qt5?

**Comment by Gnurou** [comment]
Yes, in the master branch. I need to fix a few (non-Qt5 related) bugs before making a release.

**Comment by baimafeima** [comment]
> Yes, in the master branch. I need to fix a few (non-Qt5 related) bugs before making a release.

Any updates on your planned release schedule?

**Comment by Gnurou** [comment]
I have been constantly failing at making that release for the last year or so, so no :)
