### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by samyuu** [Gnurou/tagainijisho#190]
Is it possible to somehow change the background color to something darker so that it's more pleasant for the eyes to look at while at night/dark?
Here is a sketch I made of what it might look like:

![darkmodejisho](https://cloud.githubusercontent.com/assets/25674161/22810261/e43ae2a8-ef37-11e6-8b27-f3f70abb2233.png)

**Comment by Gnurou** [comment]
I have made changes to support dark color schemes recently - if you can compile the master branch, you should be able to check them out. Otherwise please wait some more until I finally get done with that overdue release... :)

**Comment by samyuu** [comment]
Thank you for the fast response,
unfortunately I don't have any programming experience, so I will just have to wait a bit.
Also I would like to add that I really appreciate your work and that TagainiJisho has helped me a lot with my studies so far. Thanks you very much!

**Comment by Gnurou** [comment]
Thanks for the kind words. And please accept my apologies for taking so long to do that release - some bugs that need fixing first... Maybe I can release a test package though, if you are willing to try it.

**Comment by samyuu** [comment]
I'd be glad to try it out if you are willing to share a test build.
