### ISSUE TITLE
Add links for example sentences and audio

### ISSUE THREAD

**Issue by Gnurou** [Gnurou/tagainijisho#20]
Issue discussed on https://answers.launchpad.net/tagaini-jisho/+question/186137

Until tatoeba is integrated in to Tagaini, it would be nice to open the web browser to provide a list of sentences from jisho.org.

**Comment by likyng** [comment]
hey, as I value the ability to function without internet dearly, i am very interested in this issue. has any further effort been put into integrating the example sentences into the program? that is also a functionality i could see myself into looking into.

**Comment by Gnurou** [comment]
Not yet, my very limited time is dedicated to porting to Qt5 and making the code base more flexible for (maybe) an Android version. Any help is welcome.

**Comment by Eskibear** [comment]
As a long-time user of tagainijisho, it's glad to know you are planning to develop an Android version. I just wonder how much work has been done now, and I'm willing to contribute if any help is needed.

**Comment by Gnurou** [comment]
@Eskibear not much I'm afraid, real life being busier than I would like. I'm all willing to discuss and help you contribute if you have the time for this.
