### ISSUE TITLE
v 1.0.3 fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by bagustris** [Gnurou/tagainijisho#203]
Looking the official version of v 1.0.3 on Ubuntu 16.04. 
Trying the .deb on this github fails to replace v 1.0.2

**Comment by DestinFaroda** [comment]
I can't install 1.0.3 on Debian Testing. Whenever I click on "install package", nothing happens.

**Comment by Gnurou** [comment]
There was an issue with debian packages, but the one provided for version 1.1.90 (as well as future versions) should be working.
