### ISSUE TITLE
Blank overflowing "part of speech" vocabulary filter entries

### ISSUE THREAD

**Issue by Saicere** [Gnurou/tagainijisho#210]
See attached screenshot. When trying to select part-of-speech filter entries under Vocabulary, there are enough entries that many get bumped to a second column, where all the entries are blank. They are still clickable and technically working, but without the label, finding the correct one becomes an exercise in trial-and-error.

I tried reverting to the default font, but while more entries show up, the blank overflowing ones are still an issue.

![partofspeech](https://user-images.githubusercontent.com/17721693/38521187-3e0e889c-3c45-11e8-9ab3-0605107a999e.png)

**Comment by rainbyte** [comment]
This happens on my pc too... I'm using Archlinux, screen resolution is 1920x1080.

**Comment by Gnurou** [comment]
That's a known and annoying problem which has multiple causes (and part-of-speech filtering is currently broken anyway). Working on a fix for this.

**Comment by Gnurou** [comment]
Looks fixed by either the update to Qt5 or the fixing of issue #176. Closing as 1.2.0 should be released soon now.
