### ISSUE TITLE
Update kanjivg version

### ISSUE THREAD

**Issue by Arfrever** [Gnurou/tagainijisho#212]
`src/core/kanjidic2/CMakeLists.txt` contains:
```
set(KANJIVG_SOURCE https://github.com/KanjiVG/kanjivg/releases/download/r20150615-2/kanjivg-20150615-2.xml.gz)
```

Currently the newest version of KanjiVG available in https://github.com/KanjiVG/kanjivg/releases is `20160426`.
I suggest to update version referenced in this file.

**Comment by Gnurou** [comment]
Thanks for pointing this out! This is now fixed in master.
