### ISSUE TITLE
Inconsistent version

### ISSUE THREAD

**Issue by Arfrever** [Gnurou/tagainijisho#214]
When I upgraded Tagaini Jisho, there was the following message:
```
Welcome to Tagaini Jisho 2.0! Your user data has successfully been migrated from Tagaini 1.0 and you should find it as it was.

If you still have an old version of Tagaini installed, please note that changes made in Tagaini 2 will not be visible on Tagaini 1 and vice-versa. If you still have your old Tagaini version, it is recommended that you uninstall it to avoid confusion.
```

But the version reported in `Help` -> `About Tagaini Jisho` is `1.0.90` which suggests that the next release would be `1.1.0`.

So what will be version of next release? `1.1.0` or `2.0.0`?

**Comment by Gnurou** [comment]
Thanks for reporting! This confusion should now be resolved in master. The next release (built on Qt5) will be labeled 1.2. Unless I change my mind again. >_<;
