### ISSUE TITLE
Application crash

### ISSUE THREAD

**Issue by N3tFX** [Gnurou/tagainijisho#238]
In version 1.0.3 in Linux if you follow these steps the applications crashes: 

**Program > Preferences > Vocabulary entries > Printing** tab

Console message is the following:

```
Warning: QPainter::end: Painter ended with 2 saved states
Warning: Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

Warning: Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

**Comment by wsakernel** [comment]
I can't test 1.0.3 because Qt4 isn't available for me anymore. But current top-of-tree with Qt5 works for me, I can't reproduce the issue.

**Comment by N3tFX** [comment]
Maybe I have to wait until my distro updates the Qt5 libraries then. Everything else works fine, so, not a big problem for me to wait. Closing the issue.
