### ISSUE TITLE
Unable to Build latest version on windows.

### ISSUE THREAD

**Issue by Jirubizu** [Gnurou/tagainijisho#242]
I am unsure of why I am getting this issue as its very undescriptive.
`&'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe' tagainijisho.sln> cmake -G "Visual Studio 19" -DCMAKE_PREFIX_PATH=c:/Qt/5.4/msvc2010_opengl -DGUNZIP=c:/bin/gzip-1.3.12-1-bin/bin/gunzip.exe
Microsoft (R) Build Engine version 16.9.0+5e4b48a27 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1008: Only one project can be specified.
Switch: cmake

For switch syntax, type "MSBuild -help"`

Is it possible for you to publish a latest build for windows?

**Comment by Gnurou** [comment]
Windows binaries are now available for 1.1.93 and will be available for every new release from now on:

https://github.com/Gnurou/tagainijisho/releases/tag/1.1.93

The build system has also been updated, MSYS2 is now the supported way to build the program. I'm happy to add support for other ways such as VSCode is people contribute them.

Closing this issue.
