### ISSUE TITLE
kanjidic2 plugin fatal error: cannot find main database file!

### ISSUE THREAD

**Issue by eBug** [Gnurou/tagainijisho#245]
Hi,
I just cloned the repository and follow the instructions to build from sources:
```
cmake.
make
cpack -G DEB
```
it built a 1.1.90 deb package which I installed.
When I launched the program for the first time I was warned that my user database would be upgraded to tagaini-jisho 1.2
Then I got this fatal error:
```
kanjidic2 plugin fatal error: cannot find main database file!
Unrecoverable error, the program will now exit.
```

**Comment by Gnurou** [comment]
Sorry for the delayed reply, I just figured out how to solve this. Please run `cmake -DCMAKE_INSTALL_PREFIX=/usr/ .` instead of `cmake .` - for some reason the Debian package puts the database files in `/usr` instead of the default installation path...
