### ISSUE TITLE
Crash when printing custom lists.

### ISSUE THREAD

**Issue by N3tFX** [Gnurou/tagainijisho#246]
I've just build the app from source (version reported 1.1.90) and when I try to print my custom lists, the program crashes with the following message:

![Tagaini_error](https://user-images.githubusercontent.com/48089992/131391586-2aa80cd1-7676-49a0-b811-bf3846da893b.png)

If I try to print only one word, it finishes without a crash. It seems that it can't handle many words for some reason (it used to previously).

**Comment by N3tFX** [comment]
Looking at this a bit more, it seems that the problem is not the number of words in the list, but the list folders. If you only select actual words it works. But if you select even just one folder the app crashes.

**Comment by N3tFX** [comment]
@Gnurou I just tried the 1.1.93 version and this crash still happens.

**Comment by Gnurou** [comment]
Confirmed that this is consistently happening with 1.1.93 as well. The lists use a custom red-black tree implementation on top of SQLite using C++ templates that I did years ago, this is probably going to be a pain to debug, but important nonetheless.

**Comment by N3tFX** [comment]
I guess this bug is pretty hard to squash. It's still present in 1.2.0 version. Maybe the label for milestones should be changed for the 2.0 version?

By the way, thank you for continuing developing this amazing app.

**Comment by Gnurou** [comment]
Yeah, the bug was tagged for 1.2.0 but I decided to go ahead and release and fix this afterwards (1.2.1 or something) so the new version gets more testing as the beta feedback was positive. I hope to get serious on it soon.

**Comment by Gnurou** [comment]
Finally found the issue. Will release 1.2.1 to make the fix available.

**Comment by Gnurou** [comment]
W00t: https://github.com/Gnurou/tagainijisho/releases/tag/1.2.1

Sorry it took so long to fix, this was a typo introduced while replacing obsolete Qt methods...
