### ISSUE TITLE
Re-enable Windows builds and document process

### ISSUE THREAD

**Issue by Gnurou** [Gnurou/tagainijisho#250]
Find a way to cross-compile Windows installer binaries and document the process properly.

**Comment by firatakandere** [comment]
Since you started using Actions, have  you considered using Github's continues delivery for releases?

**Comment by Gnurou** [comment]
Absolutely! I have punished myself and installed a Windows 11 inside a VM to try and build natively (cross-compilation from Linux is unpractical unfortunately). I have produced working binaries from msys2 and am now trying to reproduce this from a Github Action.

**Comment by Gnurou** [comment]
Github actions now publish a working window installer (as well as a Mac one that I still need to test) with each build. The github action file acts as documentation of how to do it (and the procedure is also described in the README file). Closing this issue.
