### ISSUE TITLE
Update links on the website and the database

### ISSUE THREAD

**Issue by GrimPixel** [Gnurou/tagainijisho#254]
The links on the website are outdated.
The dictionary is outdated as well. It even doesn't contain common words like 正真正銘.

**Comment by Gnurou** [comment]
Hi,

Just-released version 1.2.0 comes with an updated JMdict and 正真正銘 is present.

Regarding the outdated links, it would help if you could specify which ones.

Closing the issue, but feel free to comment with the specific links that are broken.
