### ISSUE TITLE
Will there be an android app in the future?

### ISSUE THREAD

**Issue by ssavalenzuela** [Gnurou/tagainijisho#255]
Just asking, because this software has really helped me a lot with learning and there's no such software like yours. I'm truly thankful. I just thought maybe you could put your app on the android play store or Apple app store, maybe for free with some additional features to pay, or free and then accept donations, too. Not only will it help other people, but I think it will also help you/your company/the people involved in creating this wonderful software. Just a suggestion! THANKS SO MUCH FOR MAKING THIS AVAILABLE.

**Comment by Gnurou** [comment]
Hi,

Tagaini's codebase dates from the late 2000s which unfortunately makes it very biased towards desktop. Running Qt software on Android is not impossible, but results in a very poor experience - not to mention that the current UI would be largely inadequate.

I recognize this is a problem though, and would love to at least be able to use certain functions on mobile. The plan towards that is to transition the core code to be less dependent on Qt and maybe add a progressive web app UI as an alternative to the current Qt one, which would then be usable from Android. But this is not a small effort and is not going to happen overnight. Nonetheless, this is my plan for the longer term, maybe after I make a few more 1.2.x desktop releases to make the desktop experience stable enough for existing users.

Closing this issue as there are no real action items.
