### ISSUE TITLE
Vitesse de recherche

### ISSUE THREAD

**Issue by vintotal** [Gnurou/tagainijisho#90]
J'ai téléchargé la version 1.0.0, et je suis heureux de constater que les filtres fonctionnent bien. Merci!

Je me suis buté à un problème de vitesse. J'ai comparé avec la version 0.9.4 pour être sûr que je n'avais pas la berlue. Voici les résultats pour la recherche de vocabulaire « *的 »:

0.9.4: 8 secondes (634 résultats)
1.0.0: plus d'une minute (714 résultats)

J'ai essayé en désactivant les filtres dans la version 1.0.0, mais c'est toujours beaucoup plus lent que la version 0.9.4. À noter que durant la recherche un de mes coeurs fonctionne à plein régime. Que faire?

**Comment by Gnurou** [comment]
Issue is probably obsolete now, closing.
